language: java

jdk:
  - oraclejdk8

services:
  - postgresql

notifications:
  email: true

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE USER ferryman WITH PASSWORD 'ferryman' SUPERUSER CREATEDB CREATEROLE;" -U postgres
  - psql -c "CREATE DATABASE ferry;" -U postgres

script:
  - 'if [ "$TRAVIS_BRANCH" != "master" ]; then mvn test; fi'
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then mvn deploy; fi'